### ISSUE TITLE
nvim sub-tools (path) like bat (for file preview in fzf) broken

### ISSUE THREAD

**Issue by joehannes** [beeender/glrnvim#36]
I'm on macOS BigSur
I installed via cargo build, then creating an executable.sh with

```zsh
#!/bin/zsh

cd ~/.local/git/glrnvim
cargo run

exit 0
```

Hooking this skript up via Alfred Powerpack to a Shortcut ...
I get my glrnvim with this glrnvim.yml

```yml
backend:
  alacritty
exe_path:
  /Users/joehannes/.cargo/bin/alacritty
load_term_conf:
  true
```

Everything seemed to work, until I used a regular fuzzy finding preview and the preview was broken. That's glrnvim specific somehow, because it works in pure alacritty/nvim.

<img width="1280" alt="Bildschirmfoto 2021-04-03 um 19 43 54" src="https://user-images.githubusercontent.com/63741107/113487313-b31ed380-94b7-11eb-8468-65eba9615e4e.png">

It's a pity, I was happy for a sec, but then, I can't use it like that.
