### ISSUE TITLE
 Glrnvim is going rogue and not conforming to settings regarding terminal settings in config.yaml

### ISSUE THREAD

**Issue by anoduck** [beeender/glrnvim#71]
Terminal: Alacritty
System: OpenBSD 7.4 (Pulled from SNAPSHOT Feb 28-ish)
Editor: Nvim (obviously)

Every time I load Glrnvim now, I receive the following message in alacritty. 

```bash
[0.000123208s] [ERROR] [alacritty_config_derive] Unable to load config "/tmp/.tmpYrBeR8": Config error: did not find expected <document start> at line 2 column 1
```
This error occurs regardless of whether `load_term_conf` and/or `term_config_path` is enabled or disabled. Those settings are completely ignored, which is practically impossible, but I am just the messenger. Don't shoot the messanger.

The result is a clumsy nvim environment, as none of the settings desired are being loaded.

```yaml
# vim:fileencoding=utf-8:ft=yaml
---
# Choose the backend terminal to run neovim in.
# Current supported terminals: alacritty, urxvt, kitty, wezterm.
backend: alacritty

# Path to backend executable file
# NOTE: requires a backend key
# NOTE: old key exe_path is now deprecated but can still be used
term_exe_path: /usr/local/bin/alacritty

# Specify the Neovim executable path.
# NOTE: nvim will be used if not specified
# NOTE: For windows, e.g.: C:\tools\neovim\Neovim\bin\nvim.exe
nvim_exe_path: /usr/local/bin/nvim

# The fonts to be used. Multi fonts can be supplied.
# The first one will be set as the major font. Others will be set as
# fallback fonts according to the given orders if possible.
# NOTE: Not all backends support fallback font.
fonts:
   - FiraSans
   - Fira Code Regular Nerd Font Complete
   - IBM Plex Mono
#  - Source Code Pro
#  - monofur

# The font size to be used.
#
font_size: 9

# Set to true if the terminal's default configuration should be loaded
# first. Other glrnvim configurations will overwrite the terminal settings
# if they are set in config.yml.
# urxvt is not impacted by this setting. It always load resources according
# to the defined orders.
load_term_conf: false

# Configuration file for the selected terminal.
# NOTE:This option is not supported by urxvt.
# If this option is specified, the terminal's default config won't be loaded
# when 'load_term_conf' is true.
term_config_path: /home/user/.config/alacritty/alacritty.yml
```

My alacritty config has been stripped of comments, and linted with yamllint.

```yaml
# Stripped Alacritty config
---
window:
  decorations: none
  opacity: 0.87
  startup_mode: Maximized
font:
  normal:
    family: FiraSans
    style: Regular
  bold:
    family: FiraSans
    style: Bold
  italic:
    family: FiraSans
    style: Italic
  bold_italic:
    family: FiraSans
    style: Bold Italic
  size: 9.0
draw_bold_text_with_bright_colors: true
selection:
  save_to_clipboard: true
cursor:
  style:
    shape: Beam
live_config_reload: true
colors:
  name: Rasi
  author: ''
  primary:
    background: '0x000b1e'
    foreground: '0x0abdc6'
  cursor:
    text: '0x000b1e'
    cursor: '0x0abdc6'
  normal:
    black: '0x123e7c'
    red: '0xff0000'
    green: '0xd300c4'
    yellow: '0xf57800'
    blue: '0x123e7c'
    magenta: '0x711c91'
    cyan: '0x0abdc6'
    white: '0xd7d7d5'
  bright:
    black: '0x1c61c2'
    red: '0xff0000'
    green: '0xd300c4'
    yellow: '0xf57800'
    blue: '0x00ff00'
    magenta: '0x711c91'
    cyan: '0x0abdc6'
    white: '0xd7d7d5'
theme: Rasi
```
